server {
  listen 80;

  # Password protection for all routes
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri /index.html =404;
  # Password protection removed from nginx: Traefik will handle HTTP Basic Auth via middleware
  # auth_basic "Restricted";
  # auth_basic_user_file /usr/share/nginx/html/.htpasswd;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}