apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend-build
  namespace: aibeniq-prod
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: INSTALL_HUGGINGFACE
          value: "true"
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
  triggers:
    - type: ConfigChange
