// This file is auto-generated by @hey-api/openapi-ts

export type Body_chat_query_document = {
  file: Blob | File
}

export type Body_formconnect_process_form = {
  digitized_files?: Array<Blob | File>
  handwritten_files?: Array<Blob | File>
}

export type Body_knowledge_bases_create_knowledge_base = {
  files: Array<Blob | File>
}

export type Body_knowledge_bases_update_knowledge_base = {
  files?: Array<Blob | File> | null
  removed_file_ids?: Array<string>
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_veradoc_process_rag_checklist = {
  files: Array<Blob | File>
  handwritten_files?: Array<Blob | File>
}

export type EmbeddingModelCreate = {
  name: string
  model_id: string
  provider?: ModelProvider
  description?: string
  is_default?: boolean
}

export type EmbeddingModelPublic = {
  id?: string
  name?: string
  model_id?: string
  provider?: ModelProvider
  description?: string
  is_default?: boolean
  owner_id?: string | null
  date_created?: string
  date_modified?: string
}

export type EmbeddingModelsPublic = {
  data: Array<EmbeddingModelPublic>
  count: number
}

export type EmbeddingModelUpdate = {
  name?: string | null
  model_id?: string | null
  provider?: ModelProvider | null
  description?: string | null
  is_default?: boolean | null
}

export type EmbeddingModelValidate = {
  model_id: string
  provider: ModelProvider
}

export type FormConnectForm = {
  id?: string
  name: string
  description?: string | null
  fields: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type FormConnectResponse = {
  results: {
    [key: string]: unknown
  }
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type KnowledgeBasePublic = {
  title: string
  description?: string | null
  embedding_model_id?: string | null
  id: string
  owner_id: string
  files?: Array<{
    [key: string]: unknown
  }>
  date_created: string
  date_modified: string
  number_of_sources?: number
  embedding_model_name?: string | null
}

export type KnowledgeBasesPublic = {
  data: Array<KnowledgeBasePublic>
  count: number
}

export type LlmModelCreate = {
  name: string
  model_id: string
  provider?: ModelProvider
  description?: string
  is_default?: boolean
}

export type LlmModelPublic = {
  id?: string
  name?: string
  model_id?: string
  provider?: ModelProvider
  description?: string
  is_default?: boolean
  owner_id?: string | null
  date_created?: string
  date_modified?: string
}

export type LlmModelsPublic = {
  data: Array<LlmModelPublic>
}

export type LlmModelsValidate = {
  model_id: string
  provider: ModelProvider
}

export type Message = {
  message: string
}

export type ModelProvider = "huggingface" | "openai" | "ollama"

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type VeraDocChecklist = {
  id?: string
  name: string
  description?: string | null
  questions: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type VeraDocResponse = {
  results: {
    [key: string]: unknown
  }
}

export type ChatQueryKnowledgeBaseData = {
  kbId: string
  question: string
  useDefaultModels?: boolean
}

export type ChatQueryKnowledgeBaseResponse = unknown

export type ChatQueryDocumentData = {
  formData: Body_chat_query_document
  question?: string
  useDefaultModels?: boolean
}

export type ChatQueryDocumentResponse = unknown

export type EmbeddingModelsGetEmbeddingModelsData = {
  limit?: number
  skip?: number
}

export type EmbeddingModelsGetEmbeddingModelsResponse = EmbeddingModelsPublic

export type EmbeddingModelsCreateEmbeddingModelData = {
  requestBody: EmbeddingModelCreate
}

export type EmbeddingModelsCreateEmbeddingModelResponse = EmbeddingModelPublic

export type EmbeddingModelsGetEmbeddingModelData = {
  modelId: string
}

export type EmbeddingModelsGetEmbeddingModelResponse = EmbeddingModelPublic

export type EmbeddingModelsUpdateEmbeddingModelData = {
  modelId: string
  requestBody: EmbeddingModelUpdate
}

export type EmbeddingModelsUpdateEmbeddingModelResponse = EmbeddingModelPublic

export type EmbeddingModelsDeleteEmbeddingModelData = {
  modelId: string
}

export type EmbeddingModelsDeleteEmbeddingModelResponse = Message

export type EmbeddingModelsGetDefaultEmbeddingModelResponse =
  EmbeddingModelPublic

export type EmbeddingModelsSetDefaultEmbeddingModelData = {
  modelId: string
}

export type EmbeddingModelsSetDefaultEmbeddingModelResponse =
  EmbeddingModelPublic

export type EmbeddingModelsValidateEmbeddingModelData = {
  requestBody: EmbeddingModelValidate
}

export type EmbeddingModelsValidateEmbeddingModelResponse = Message

export type EmbeddingModelsCheckApiKeyConfiguredData = {
  provider: string
}

export type EmbeddingModelsCheckApiKeyConfiguredResponse = Message

export type FormconnectProcessFormData = {
  fields: string
  formData?: Body_formconnect_process_form
}

export type FormconnectProcessFormResponse = FormConnectResponse

export type FormconnectGetFormsResponse = Array<FormConnectForm>

export type FormconnectCreateFormData = {
  requestBody: FormConnectForm
}

export type FormconnectCreateFormResponse = FormConnectForm

export type FormconnectGetFormData = {
  formId: string
}

export type FormconnectGetFormResponse = FormConnectForm

export type FormconnectUpdateFormData = {
  formId: string
  requestBody: FormConnectForm
}

export type FormconnectUpdateFormResponse = FormConnectForm

export type FormconnectDeleteFormData = {
  formId: string
}

export type FormconnectDeleteFormResponse = unknown

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type KnowledgeBasesReadKnowledgeBasesData = {
  limit?: number
  skip?: number
}

export type KnowledgeBasesReadKnowledgeBasesResponse = KnowledgeBasesPublic

export type KnowledgeBasesCreateKnowledgeBaseData = {
  description?: string | null
  embeddingModelId?: string | null
  formData: Body_knowledge_bases_create_knowledge_base
  title: string
}

export type KnowledgeBasesCreateKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesReadKnowledgeBaseData = {
  id: string
}

export type KnowledgeBasesReadKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesUpdateKnowledgeBaseData = {
  description?: string | null
  embeddingModelId?: string | null
  formData?: Body_knowledge_bases_update_knowledge_base
  id: string
  title?: string | null
}

export type KnowledgeBasesUpdateKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesDeleteKnowledgeBaseData = {
  id: string
}

export type KnowledgeBasesDeleteKnowledgeBaseResponse = Message

export type LlmModelsGetLlmModelsData = {
  limit?: number
  skip?: number
}

export type LlmModelsGetLlmModelsResponse = LlmModelsPublic

export type LlmModelsCreateLlmModelData = {
  requestBody: LlmModelCreate
}

export type LlmModelsCreateLlmModelResponse = LlmModelPublic

export type LlmModelsGetDefaultLlmModelResponse = LlmModelPublic

export type LlmModelsDeleteLlmModelData = {
  modelId: string
}

export type LlmModelsDeleteLlmModelResponse = Message

export type LlmModelsValidateLlmModelData = {
  requestBody: LlmModelsValidate
}

export type LlmModelsValidateLlmModelResponse = Message

export type LlmModelsSetDefaultLlmModelData = {
  modelId: string
}

export type LlmModelsSetDefaultLlmModelResponse = LlmModelPublic

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

export type VeradocProcessRagChecklistData = {
  formData: Body_veradoc_process_rag_checklist
  knowledgeBaseId: string
  questions: string
}

export type VeradocProcessRagChecklistResponse = VeraDocResponse

export type VeradocGetChecklistsResponse = Array<VeraDocChecklist>

export type VeradocCreateChecklistData = {
  requestBody: VeraDocChecklist
}

export type VeradocCreateChecklistResponse = VeraDocChecklist

export type VeradocGetChecklistData = {
  checklistId: string
}

export type VeradocGetChecklistResponse = VeraDocChecklist

export type VeradocUpdateChecklistData = {
  checklistId: string
  requestBody: VeraDocChecklist
}

export type VeradocUpdateChecklistResponse = VeraDocChecklist

export type VeradocDeleteChecklistData = {
  checklistId: string
}

export type VeradocDeleteChecklistResponse = unknown
