// This file is auto-generated by @hey-api/openapi-ts

export type Body_chat_query_document = {
  file?: Blob | File
}

export type Body_formconnect_process_form = {
  digitized_files?: Array<Blob | File>
  handwritten_files?: Array<Blob | File>
}

export type Body_knowledge_bases_create_knowledge_base = {
  files: Array<Blob | File>
}

export type Body_knowledge_bases_update_knowledge_base = {
  files?: Array<Blob | File> | null
  removed_file_ids?: Array<string> | null
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_twincheck_compare_documents = {
  document1: Blob | File
  document2: Blob | File
}

export type Body_veradoc_process_rag_checklist = {
  files: Array<Blob | File>
}

/**
 * Response model for document query endpoint
 */
export type DocumentQueryResponse = {
  answer: string
  sources: Array<Source>
  session_id: string
  rephrased_question: string
}

export type DocxRequest = {
  content: string
  title?: string | null
}

/**
 * Model for embedding model information.
 */
export type EmbeddingModelInfo = {
  id: string
  provider: string
  model_name: string
  dimensions: number
  max_input_length?: number | null
  cost_per_1M_tokens?: number | null
  description?: string | null
}

export type FormConnectDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type FormConnectDetailResponse = {
  id: string
  date_created: string
  fields: string
  file_names: Array<string>
  results: {
    [key: string]: unknown
  }
  feedback: FormConnectDetailFeedback
}

export type FormConnectForm = {
  id?: string
  name: string
  description?: string | null
  fields: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type FormConnectResponse = {
  results: {
    [key: string]: unknown
  }
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type KnowledgeBasePublic = {
  title: string
  description?: string | null
  embedding_model_id?: string
  id: string
  owner_id: string
  files?: Array<{
    [key: string]: unknown
  }>
  date_created: string
  date_modified: string
  number_of_sources?: number
  embedding_model: EmbeddingModelInfo
}

export type KnowledgeBasesPublic = {
  data: Array<KnowledgeBasePublic>
  count: number
}

/**
 * Model for LLM model information.
 */
export type LlmModelSpec = {
  id: string
  provider: LlmProvider
  model_name: string
  context_length?: number | null
  max_output_tokens?: number | null
  cost_per_1M_input_tokens?: number | null
  cost_per_1M_output_tokens?: number | null
  supports_streaming?: boolean
  supports_function_calling?: boolean
  supports_vision?: boolean
  description?: string | null
}

/**
 * Model for LLM provider information.
 */
export type LlmProvider = {
  id: string
  name: string
  required_env_vars: Array<string>
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Response model for knowledge base query endpoint
 */
export type QueryResponse = {
  answer: string
  sources: Array<Source>
  session_id: string
  rephrased_question: string
}

export type ReportGenieDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type ReportGenieDetailResponse = {
  id: string
  date_created: string
  kb_name: string
  kb_id: string
  sections: string
  results: ReportGenieDetailResults
  feedback: ReportGenieDetailFeedback
}

export type ReportGenieDetailResults = {
  full_report: string
  sections?: Array<ReportGenieSection>
}

export type ReportGenieHistoryItem = {
  id: string
  date_created: string
  title: string
  sections: string
  kb_id: string
  section_count: number
  kb_name: string
  outline_name: string
  has_feedback: boolean
  feedback?: {
    [key: string]: unknown
  } | null
  user_name?: string | null
}

export type ReportGenieOutline = {
  id?: string
  name: string
  description?: string | null
  sections: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type ReportGenieRequest = {
  knowledge_base_id: string
  sections: string
  outline_id: string
}

export type ReportGenieResponse = {
  results: ReportGenieResults
}

export type ReportGenieResults = {
  full_report: string
  sections?: Array<ReportGenieSection>
}

export type ReportGenieSection = {
  title: string
  content: string
  source_citations?: Array<ReportGenieSourceCitation>
}

export type ReportGenieSourceCitation = {
  content: string
  source_metadata: ReportGenieSourceMetadata
}

export type ReportGenieSourceMetadata = {
  source_id?: string
  url?: string
  title?: string
  author?: string
}

/**
 * Source document snippet with metadata
 */
export type Source = {
  content: string
  metadata: SourceMetadata
}

export type SourceContentResponse = {
  id: string
  name: string
  data_base64: string
  content_type: string
}

/**
 * Metadata for document sources
 */
export type SourceMetadata = {
  source_name?: string | null
  source_id?: string | null
  [key: string]: unknown
}

/**
 * Response model for text query endpoint
 */
export type TextQueryResponse = {
  answer: string
  session_id: string
  rephrased_question: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type TwinCheckDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type TwinCheckDetailResponse = {
  id: string
  date_created: string
  document1_name: string
  document2_name: string
  comparison_topics: string
  results: TwinCheckDetailResults
  feedback: TwinCheckDetailFeedback
}

export type TwinCheckDetailResults = {
  summary: string
  topic_analysis?: Array<{
    [key: string]: unknown
  }>
  interaction_id: string
}

export type TwinCheckResponse = {
  results: {
    [key: string]: unknown
  }
}

export type TwinCheckTopicList = {
  id?: string
  name: string
  description?: string | null
  topics: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  default_embedding_model?: string
  default_llm?: string
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  default_embedding_model?: string
  default_llm?: string
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  default_embedding_model?: string
  default_llm?: string
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type VeraDocChecklist = {
  id?: string
  name: string
  description?: string | null
  questions: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type VeraDocChecklistCreate = {
  name: string
  description?: string | null
  questions: string
}

export type VeraDocChecklistUpdate = {
  name?: string | null
  description?: string | null
  questions?: string | null
}

export type VeraDocDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type VeraDocDetailResponse = {
  id: string
  date_created: string
  document_name?: string | null
  kb_name?: string | null
  kb_id?: string | null
  questions?: string | null
  results: VeraDocDetailResults
  feedback: VeraDocDetailFeedback
}

export type VeraDocDetailResults = {
  final_evaluation: string
  qa_pairs?: Array<{
    [key: string]: unknown
  }>
  interaction_id: string
}

export type VeraDocHistoryItem = {
  id: string
  date_created: string
  title: string
  document_name: string
  kb_id: string
  qa_count: number
  kb_name: string
  questions: string
  final_evaluation: string
  has_feedback: boolean
  feedback?: {
    [key: string]: unknown
  } | null
  user_name?: string | null
}

export type VeraDocResponse = {
  results: {
    [key: string]: unknown
  }
}

export type ChatQueryKnowledgeBaseData = {
  chatHistory?: string | null
  isFollowUp?: boolean
  kbId: string
  question: string
  sessionId?: string | null
}

export type ChatQueryKnowledgeBaseResponse = QueryResponse

export type ChatQueryDocumentData = {
  chatHistory?: string | null
  formData?: Body_chat_query_document
  isFollowUp?: boolean
  question?: string | null
  sessionId?: string | null
}

export type ChatQueryDocumentResponse = DocumentQueryResponse

export type ChatQueryTextData = {
  chatHistory?: string | null
  isFollowUp?: boolean
  question: string
  sessionId?: string | null
}

export type ChatQueryTextResponse = TextQueryResponse

export type FeedbackSubmitFeedbackData = {
  feedback: string
  feedbackText?: string | null
  interactionId: string
}

export type FeedbackSubmitFeedbackResponse = Message

export type FilesGetSourceContentData = {
  sourceId: string
}

export type FilesGetSourceContentResponse = SourceContentResponse

export type FormconnectProcessFormData = {
  fields: string
  formData?: Body_formconnect_process_form
}

export type FormconnectProcessFormResponse = FormConnectResponse

export type FormconnectGetFormsResponse = Array<FormConnectForm>

export type FormconnectCreateFormData = {
  requestBody: FormConnectForm
}

export type FormconnectCreateFormResponse = FormConnectForm

export type FormconnectGetFormData = {
  formId: string
}

export type FormconnectGetFormResponse = FormConnectForm

export type FormconnectUpdateFormData = {
  formId: string
  requestBody: FormConnectForm
}

export type FormconnectUpdateFormResponse = FormConnectForm

export type FormconnectDeleteFormData = {
  formId: string
}

export type FormconnectDeleteFormResponse = Message

export type FormconnectGetFormDetailData = {
  interactionId: string
}

export type FormconnectGetFormDetailResponse = FormConnectDetailResponse

export type FormconnectGetFormHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type FormconnectGetFormHistoryResponse = Array<{
  [key: string]: unknown
}>

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type KnowledgeBasesReadKnowledgeBasesData = {
  limit?: number
  skip?: number
}

export type KnowledgeBasesReadKnowledgeBasesResponse = KnowledgeBasesPublic

export type KnowledgeBasesCreateKnowledgeBaseData = {
  description?: string | null
  embeddingModelId?: string
  formData: Body_knowledge_bases_create_knowledge_base
  title: string
}

export type KnowledgeBasesCreateKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesReadKnowledgeBaseData = {
  id: string
}

export type KnowledgeBasesReadKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesUpdateKnowledgeBaseData = {
  description?: string | null
  formData?: Body_knowledge_bases_update_knowledge_base
  id: string
  title?: string | null
}

export type KnowledgeBasesUpdateKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesDeleteKnowledgeBaseData = {
  id: string
}

export type KnowledgeBasesDeleteKnowledgeBaseResponse = Message

export type LlmModelsGetLlmModelsResponse = Array<LlmModelSpec>

export type LlmModelsGetAvailableProvidersResponse = Array<string>

export type LlmModelsGetDefaultLlmModelResponse = LlmModelSpec

export type LlmModelsValidateLlmModelData = {
  modelId: string
}

export type LlmModelsValidateLlmModelResponse = Message

export type LlmModelsCheckApiKeyConfiguredData = {
  provider: string
}

export type LlmModelsCheckApiKeyConfiguredResponse = Message

export type LlmModelsSetDefaultLlmModelData = {
  modelId: string
}

export type LlmModelsSetDefaultLlmModelResponse = LlmModelSpec

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type ModelsGetEmbeddingProvidersResponse = Array<string>

export type ModelsGetEmbeddingModelsRegistryResponse = Array<EmbeddingModelInfo>

export type ModelsGetDefaultEmbeddingModelResponse = EmbeddingModelInfo

export type ModelsGetLlmProvidersResponse = Array<string>

export type ModelsGetLlmModelsResponse = Array<LlmModelSpec>

export type ModelsGetDefaultLlmModelResponse = LlmModelSpec

export type ModelsSetDefaultLlmModelData = {
  modelId: string
}

export type ModelsSetDefaultLlmModelResponse = LlmModelSpec

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type ReportgenieGenerateReportData = {
  requestBody: ReportGenieRequest
}

export type ReportgenieGenerateReportResponse = ReportGenieResponse

export type ReportgenieGetOutlinesResponse = Array<ReportGenieOutline>

export type ReportgenieCreateOutlineData = {
  requestBody: ReportGenieOutline
}

export type ReportgenieCreateOutlineResponse = ReportGenieOutline

export type ReportgenieGetOutlineData = {
  outlineId: string
}

export type ReportgenieGetOutlineResponse = ReportGenieOutline

export type ReportgenieUpdateOutlineData = {
  outlineId: string
  requestBody: ReportGenieOutline
}

export type ReportgenieUpdateOutlineResponse = ReportGenieOutline

export type ReportgenieDeleteOutlineData = {
  outlineId: string
}

export type ReportgenieDeleteOutlineResponse = Message

export type ReportgenieGenerateDocxData = {
  requestBody: DocxRequest
}

export type ReportgenieGenerateDocxResponse = unknown

export type ReportgenieGetReportHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type ReportgenieGetReportHistoryResponse = Array<ReportGenieHistoryItem>

export type ReportgenieGetReportDetailData = {
  reportId: string
}

export type ReportgenieGetReportDetailResponse = ReportGenieDetailResponse

export type TwincheckCompareDocumentsData = {
  comparisonTopics: string
  formData: Body_twincheck_compare_documents
}

export type TwincheckCompareDocumentsResponse = TwinCheckResponse

export type TwincheckGetComparisonHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type TwincheckGetComparisonHistoryResponse = Array<{
  [key: string]: unknown
}>

export type TwincheckGetComparisonDetailData = {
  comparisonId: string
}

export type TwincheckGetComparisonDetailResponse = TwinCheckDetailResponse

export type TwincheckGetComparisonsResponse = Array<TwinCheckTopicList>

export type TwincheckCreateComparisonData = {
  requestBody: TwinCheckTopicList
}

export type TwincheckCreateComparisonResponse = TwinCheckTopicList

export type TwincheckGetComparisonData = {
  comparisonId: string
}

export type TwincheckGetComparisonResponse = TwinCheckTopicList

export type TwincheckUpdateComparisonData = {
  comparisonId: string
  requestBody: TwinCheckTopicList
}

export type TwincheckUpdateComparisonResponse = TwinCheckTopicList

export type TwincheckDeleteComparisonData = {
  comparisonId: string
}

export type TwincheckDeleteComparisonResponse = Message

export type TwincheckGenerateDocxData = {
  requestBody: DocxRequest
}

export type TwincheckGenerateDocxResponse = unknown

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

export type VeradocProcessRagChecklistData = {
  formData: Body_veradoc_process_rag_checklist
  knowledgeBaseId: string
  questions: string
}

export type VeradocProcessRagChecklistResponse = VeraDocResponse

export type VeradocGetChecklistsResponse = Array<VeraDocChecklist>

export type VeradocCreateChecklistData = {
  requestBody: VeraDocChecklistCreate
}

export type VeradocCreateChecklistResponse = VeraDocChecklist

export type VeradocGetChecklistData = {
  checklistId: string
}

export type VeradocGetChecklistResponse = VeraDocChecklist

export type VeradocUpdateChecklistData = {
  checklistId: string
  requestBody: VeraDocChecklistUpdate
}

export type VeradocUpdateChecklistResponse = VeraDocChecklist

export type VeradocDeleteChecklistData = {
  checklistId: string
}

export type VeradocDeleteChecklistResponse = Message

export type VeradocGetVeradocHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type VeradocGetVeradocHistoryResponse = Array<VeraDocHistoryItem>

export type VeradocGetVeradocDetailData = {
  reportId: string
}

export type VeradocGetVeradocDetailResponse = VeraDocDetailResponse

export type VeradocGenerateDocxData = {
  requestBody: DocxRequest
}

export type VeradocGenerateDocxResponse = unknown
