// This file is auto-generated by @hey-api/openapi-ts

export type Body_chat_query_document = {
  files?: Array<Blob | File>
}

export type Body_formconnect_process_form = {
  digitized_files?: Array<Blob | File>
  handwritten_files?: Array<Blob | File>
}

export type Body_knowledge_bases_create_knowledge_base = {
  files: Array<Blob | File>
}

export type Body_knowledge_bases_update_knowledge_base = {
  files?: Array<Blob | File> | null
  removed_file_ids?: Array<string>
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_twincheck_compare_documents = {
  document1: Blob | File
  document2: Blob | File
}

export type Body_veradoc_optimize_checklist = {
  files: Array<Blob | File>
}

export type Body_veradoc_process_rag_checklist = {
  files: Array<Blob | File>
  handwritten_files?: Array<Blob | File>
}

/**
 * Request model for general chat endpoint
 */
export type ChatRequest = {
  prompt: string
  knowledge_base_id?: string | null
  search_type?: string
  chat_history?: string | null
  session_id?: string | null
  is_follow_up?: boolean
}

export type ChecklistSuggestion = {
  original_question: string
  suggested_question: string
  reason: string
  current_answer: string
  needs_revision: boolean
}

/**
 * Response model for document query endpoint
 */
export type DocumentQueryResponse = {
  answer: string
  sources: Array<Source>
  session_id: string
  rephrased_question: string
}

export type DocxRequest = {
  content: string
}

export type EmbeddingModelCreate = {
  name: string
  model_id: string
  provider?: ModelProvider
  description?: string
}

export type EmbeddingModelPublic = {
  id?: string
  name?: string
  model_id?: string
  provider?: ModelProvider
  description?: string
  owner_id?: string | null
  date_created?: string
  date_modified?: string
}

export type EmbeddingModelsPublic = {
  data: Array<EmbeddingModelPublic>
  count: number
}

export type EmbeddingModelUpdate = {
  name?: string | null
  model_id?: string | null
  provider?: ModelProvider | null
  description?: string | null
}

export type EmbeddingModelValidate = {
  model_id: string
  provider: ModelProvider
}

export type FormConnectDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type FormConnectDetailResponse = {
  id: string
  date_created: string
  fields: string
  file_names: Array<string>
  results: {
    [key: string]: unknown
  }
  feedback: FormConnectDetailFeedback
}

export type FormConnectForm = {
  id?: string
  name: string
  description?: string | null
  fields: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type FormConnectResponse = {
  results: {
    [key: string]: unknown
  }
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type KnowledgeBasePublic = {
  title: string
  description?: string | null
  embedding_model_id?: string | null
  id: string
  owner_id: string
  files?: Array<{
    [key: string]: unknown
  }>
  date_created: string
  date_modified: string
  number_of_sources?: number
  embedding_model_name?: string | null
}

export type KnowledgeBasesPublic = {
  data: Array<KnowledgeBasePublic>
  count: number
}

export type LanguageUpdate = {
  preferred_language: string
}

export type LlmModelCreate = {
  name: string
  model_id: string
  provider?: ModelProvider
  description?: string
}

export type LlmModelPublic = {
  id?: string
  name?: string
  model_id?: string
  provider?: ModelProvider
  description?: string
  owner_id?: string | null
  date_created?: string
  date_modified?: string
}

export type LlmModelsPublic = {
  data: Array<LlmModelPublic>
  count: number
}

export type LlmModelsValidate = {
  model_id: string
  provider: ModelProvider
}

export type Message = {
  message: string
}

export type ModelProvider =
  | "huggingface"
  | "openai"
  | "ollama"
  | "replicate"
  | "aws"

export type NewPassword = {
  token: string
  new_password: string
}

export type OptimizedChecklistResponse = {
  original_questions: Array<string>
  suggestions: Array<ChecklistSuggestion>
  optimized_questions: Array<string>
  analysis_summary: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Response model for knowledge base query endpoint
 */
export type QueryResponse = {
  answer: string
  sources: Array<Source>
  session_id: string
  rephrased_question: string
}

export type ReportGenieDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type ReportGenieDetailResponse = {
  id: string
  date_created: string
  kb_name: string
  kb_id: string
  sections: string
  results: ReportGenieDetailResults
  feedback: ReportGenieDetailFeedback
}

export type ReportGenieDetailResults = {
  full_report: string
  sections?: Array<{
    [key: string]: unknown
  }>
}

export type ReportGenieOutline = {
  id?: string
  name: string
  description?: string | null
  sections: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type ReportGenieResponse = {
  results: {
    [key: string]: unknown
  }
}

/**
 * Source document snippet with metadata
 */
export type Source = {
  content: string
  metadata: SourceMetadata
}

export type SourceContentResponse = {
  id: string
  name: string
  data_base64: string
  content_type: string
}

/**
 * Metadata for document sources
 */
export type SourceMetadata = {
  source?: string | null
  source_data_id?: string | null
  page?: number | null
  [key: string]: unknown
}

/**
 * Response model for text query endpoint
 */
export type TextQueryResponse = {
  answer: string
  session_id: string
  rephrased_question: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type TwinCheckDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type TwinCheckDetailResponse = {
  id: string
  date_created: string
  document1_name: string
  document2_name: string
  comparison_topics: string
  results: TwinCheckDetailResults
  feedback: TwinCheckDetailFeedback
}

export type TwinCheckDetailResults = {
  summary: string
  topic_analysis?: Array<{
    [key: string]: unknown
  }>
  interaction_id: string
}

export type TwinCheckResponse = {
  results: {
    [key: string]: unknown
  }
}

export type TwinCheckTopicList = {
  id?: string
  name: string
  description?: string | null
  topics: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type User = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id?: string
  hashed_password: string
  default_llm?: string | null
  default_embedding_model?: string | null
  preferred_language?: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
  preferred_language: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
  preferred_language?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
  preferred_language?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type VeraDocChecklist = {
  id?: string
  name: string
  description?: string | null
  questions: string
  owner_id: string
  date_created?: string
  date_modified?: string
}

export type VeraDocDetailFeedback = {
  feedback?: string | null
  feedbackText?: string | null
  feedbackDate?: string | null
}

export type VeraDocDetailResponse = {
  id: string
  date_created: string
  document_name?: string | null
  kb_name?: string | null
  kb_id?: string | null
  questions?: string | null
  results: VeraDocDetailResults
  feedback: VeraDocDetailFeedback
}

export type VeraDocDetailResults = {
  final_evaluation: string
  qa_pairs?: Array<{
    [key: string]: unknown
  }>
  interaction_id: string
}

export type VeraDocResponse = {
  results: {
    [key: string]: unknown
  }
}

export type ChatQueryKnowledgeBaseData = {
  chatHistory?: string
  isFollowUp?: boolean
  kbId: string
  question: string
  searchMode?: string
  sessionId?: string
  useDefaultModels?: boolean
}

export type ChatQueryKnowledgeBaseResponse = QueryResponse

export type ChatQueryDocumentData = {
  chatHistory?: string
  formData?: Body_chat_query_document
  isFollowUp?: boolean
  question?: string
  searchMode?: string
  sessionId?: string
  useDefaultModels?: boolean
}

export type ChatQueryDocumentResponse = DocumentQueryResponse

export type ChatQueryTextData = {
  chatHistory?: string
  isFollowUp?: boolean
  question: string
  sessionId?: string
}

export type ChatQueryTextResponse = TextQueryResponse

export type ChatChatData = {
  requestBody: ChatRequest
}

export type ChatChatResponse = QueryResponse

export type EmbeddingModelsGetAvailableProvidersResponse = {
  [key: string]: Array<string>
}

export type EmbeddingModelsGetEmbeddingModelsData = {
  limit?: number
  skip?: number
}

export type EmbeddingModelsGetEmbeddingModelsResponse = EmbeddingModelsPublic

export type EmbeddingModelsCreateEmbeddingModelData = {
  requestBody: EmbeddingModelCreate
}

export type EmbeddingModelsCreateEmbeddingModelResponse = EmbeddingModelPublic

export type EmbeddingModelsGetDefaultEmbeddingModelResponse =
  EmbeddingModelPublic

export type EmbeddingModelsGetEmbeddingModelData = {
  modelId: string
}

export type EmbeddingModelsGetEmbeddingModelResponse = EmbeddingModelPublic

export type EmbeddingModelsUpdateEmbeddingModelData = {
  modelId: string
  requestBody: EmbeddingModelUpdate
}

export type EmbeddingModelsUpdateEmbeddingModelResponse = EmbeddingModelPublic

export type EmbeddingModelsDeleteEmbeddingModelData = {
  modelId: string
}

export type EmbeddingModelsDeleteEmbeddingModelResponse = Message

export type EmbeddingModelsSetDefaultEmbeddingModelData = {
  modelId: string
}

export type EmbeddingModelsSetDefaultEmbeddingModelResponse =
  EmbeddingModelPublic

export type EmbeddingModelsValidateEmbeddingModelData = {
  requestBody: EmbeddingModelValidate
}

export type EmbeddingModelsValidateEmbeddingModelResponse = Message

export type EmbeddingModelsCheckApiKeyConfiguredData = {
  provider: string
}

export type EmbeddingModelsCheckApiKeyConfiguredResponse = Message

export type FeedbackSubmitFeedbackData = {
  feedback: string
  feedbackText?: string | null
  interactionId: string
}

export type FeedbackSubmitFeedbackResponse = Message

export type FilesGetSourceContentData = {
  sourceId: string
}

export type FilesGetSourceContentResponse = SourceContentResponse

export type FormconnectProcessFormData = {
  fields: string
  formData?: Body_formconnect_process_form
}

export type FormconnectProcessFormResponse = FormConnectResponse

export type FormconnectGetFormsResponse = Array<FormConnectForm>

export type FormconnectCreateFormData = {
  requestBody: FormConnectForm
}

export type FormconnectCreateFormResponse = FormConnectForm

export type FormconnectGetFormData = {
  formId: string
}

export type FormconnectGetFormResponse = FormConnectForm

export type FormconnectUpdateFormData = {
  formId: string
  requestBody: FormConnectForm
}

export type FormconnectUpdateFormResponse = FormConnectForm

export type FormconnectDeleteFormData = {
  formId: string
}

export type FormconnectDeleteFormResponse = Message

export type FormconnectGetFormDetailData = {
  interactionId: string
}

export type FormconnectGetFormDetailResponse = FormConnectDetailResponse

export type FormconnectGetFormHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type FormconnectGetFormHistoryResponse = Array<{
  [key: string]: unknown
}>

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type KnowledgeBasesReadKnowledgeBasesData = {
  limit?: number
  skip?: number
}

export type KnowledgeBasesReadKnowledgeBasesResponse = KnowledgeBasesPublic

export type KnowledgeBasesCreateKnowledgeBaseData = {
  description?: string | null
  embeddingModelId?: string | null
  formData: Body_knowledge_bases_create_knowledge_base
  title: string
}

export type KnowledgeBasesCreateKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesReadKnowledgeBaseData = {
  id: string
}

export type KnowledgeBasesReadKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesUpdateKnowledgeBaseData = {
  description?: string | null
  embeddingModelId?: string | null
  formData?: Body_knowledge_bases_update_knowledge_base
  id: string
  title?: string | null
}

export type KnowledgeBasesUpdateKnowledgeBaseResponse = KnowledgeBasePublic

export type KnowledgeBasesDeleteKnowledgeBaseData = {
  id: string
}

export type KnowledgeBasesDeleteKnowledgeBaseResponse = Message

export type LlmModelsGetLlmModelsData = {
  limit?: number
  skip?: number
}

export type LlmModelsGetLlmModelsResponse = LlmModelsPublic

export type LlmModelsCreateLlmModelData = {
  requestBody: LlmModelCreate
}

export type LlmModelsCreateLlmModelResponse = LlmModelPublic

export type LlmModelsGetDefaultLlmModelResponse = LlmModelPublic

export type LlmModelsDeleteLlmModelData = {
  modelId: string
}

export type LlmModelsDeleteLlmModelResponse = Message

export type LlmModelsValidateLlmModelData = {
  requestBody: LlmModelsValidate
}

export type LlmModelsValidateLlmModelResponse = Message

export type LlmModelsSetDefaultLlmModelData = {
  modelId: string
}

export type LlmModelsSetDefaultLlmModelResponse = LlmModelPublic

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type ReportgenieGenerateReportData = {
  knowledgeBaseId: string
  outlineId: string
  searchMode?: string
  sections: string
}

export type ReportgenieGenerateReportResponse = ReportGenieResponse

export type ReportgenieGetOutlinesResponse = Array<ReportGenieOutline>

export type ReportgenieCreateOutlineData = {
  requestBody: ReportGenieOutline
}

export type ReportgenieCreateOutlineResponse = ReportGenieOutline

export type ReportgenieGetOutlineData = {
  outlineId: string
}

export type ReportgenieGetOutlineResponse = ReportGenieOutline

export type ReportgenieUpdateOutlineData = {
  outlineId: string
  requestBody: ReportGenieOutline
}

export type ReportgenieUpdateOutlineResponse = ReportGenieOutline

export type ReportgenieDeleteOutlineData = {
  outlineId: string
}

export type ReportgenieDeleteOutlineResponse = Message

export type ReportgenieGenerateDocxData = {
  requestBody: DocxRequest
}

export type ReportgenieGenerateDocxResponse = unknown

export type ReportgenieGenerateCsvData = {
  requestBody: DocxRequest
}

export type ReportgenieGenerateCsvResponse = unknown

export type ReportgenieGetReportHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type ReportgenieGetReportHistoryResponse = Array<{
  [key: string]: unknown
}>

export type ReportgenieGetReportDetailData = {
  reportId: string
}

export type ReportgenieGetReportDetailResponse = ReportGenieDetailResponse

export type TwincheckCompareDocumentsData = {
  comparisonTopics: string
  formData: Body_twincheck_compare_documents
}

export type TwincheckCompareDocumentsResponse = TwinCheckResponse

export type TwincheckGetComparisonHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type TwincheckGetComparisonHistoryResponse = Array<{
  [key: string]: unknown
}>

export type TwincheckGetComparisonDetailData = {
  comparisonId: string
}

export type TwincheckGetComparisonDetailResponse = TwinCheckDetailResponse

export type TwincheckGetComparisonsResponse = Array<TwinCheckTopicList>

export type TwincheckCreateComparisonData = {
  requestBody: TwinCheckTopicList
}

export type TwincheckCreateComparisonResponse = TwinCheckTopicList

export type TwincheckGetComparisonData = {
  comparisonId: string
}

export type TwincheckGetComparisonResponse = TwinCheckTopicList

export type TwincheckUpdateComparisonData = {
  comparisonId: string
  requestBody: TwinCheckTopicList
}

export type TwincheckUpdateComparisonResponse = TwinCheckTopicList

export type TwincheckDeleteComparisonData = {
  comparisonId: string
}

export type TwincheckDeleteComparisonResponse = Message

export type TwincheckGenerateDocxData = {
  requestBody: DocxRequest
}

export type TwincheckGenerateDocxResponse = unknown

export type UsersUpdateLanguageData = {
  requestBody: LanguageUpdate
}

export type UsersUpdateLanguageResponse = User

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

export type VeradocProcessRagChecklistData = {
  formData: Body_veradoc_process_rag_checklist
  knowledgeBaseId: string
  questions: string
}

export type VeradocProcessRagChecklistResponse = VeraDocResponse

export type VeradocGetChecklistsResponse = Array<VeraDocChecklist>

export type VeradocCreateChecklistData = {
  requestBody: VeraDocChecklist
}

export type VeradocCreateChecklistResponse = VeraDocChecklist

export type VeradocGetChecklistData = {
  checklistId: string
}

export type VeradocGetChecklistResponse = VeraDocChecklist

export type VeradocUpdateChecklistData = {
  checklistId: string
  requestBody: VeraDocChecklist
}

export type VeradocUpdateChecklistResponse = VeraDocChecklist

export type VeradocDeleteChecklistData = {
  checklistId: string
}

export type VeradocDeleteChecklistResponse = Message

export type VeradocGetVeradocHistoryData = {
  limit?: number
  showAll?: boolean
  skip?: number
}

export type VeradocGetVeradocHistoryResponse = Array<{
  [key: string]: unknown
}>

export type VeradocGetVeradocDetailData = {
  reportId: string
}

export type VeradocGetVeradocDetailResponse = VeraDocDetailResponse

export type VeradocOptimizeChecklistData = {
  formData: Body_veradoc_optimize_checklist
  knowledgeBaseId: string
  questions: string
  targetAnswers?: string
}

export type VeradocOptimizeChecklistResponse = OptimizedChecklistResponse

export type VeradocGenerateDocxData = {
  requestBody: DocxRequest
}

export type VeradocGenerateDocxResponse = unknown

export type VeradocGenerateCsvData = {
  requestBody: DocxRequest
}

export type VeradocGenerateCsvResponse = unknown
