"""Add data column to KnowledgeBase

Revision ID: 006e47239e5c
Revises: 178e9df64f30
Create Date: 2025-05-22 19:42:17.002159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '006e47239e5c'
down_revision = '178e9df64f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE modelprovider ADD VALUE 'replicate'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
