"""Add data column to KnowledgeBase

Revision ID: 178e9df64f30
Revises: ffd0f9521272
Create Date: 2025-05-22 16:41:01.057110

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '178e9df64f30'
down_revision = 'ffd0f9521272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # modify the column with explicit USING clause
    op.execute("""
        ALTER TABLE llmmodel 
        ALTER COLUMN provider TYPE modelprovider 
        USING provider::modelprovider
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llmmodel', 'provider',
               existing_type=sa.Enum('huggingface', 'openai', 'ollama', 'replicate', name='modelprovider', create_constraint=True),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
