"""rename LlmInteraction to ToolInteraction, add better typing

Revision ID: 20b2b6de3bb5
Revises: a1b2c3d4e5f6
Create Date: 2025-07-09 11:14:07.206095

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20b2b6de3bb5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('functionality', sa.Enum('CHATBOT', 'VERADOC', 'FORMCONNECT', 'REPORTGENIE', 'TWINCHECK', name='tool'), nullable=False),
    sa.Column('input_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Enum('POSITIVE', 'NEGATIVE', name='toolfeedback'), nullable=True),
    sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_interactions_functionality'), 'tool_interactions', ['functionality'], unique=False)
    op.drop_index(op.f('ix_llm_interactions_functionality'), table_name='llm_interactions')
    op.drop_table('llm_interactions')
    op.drop_index(op.f('ix_embeddingmodel_name'), table_name='embeddingmodel')
    op.drop_table('embeddingmodel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddingmodel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('huggingface', 'openai', 'ollama', 'replicate', 'aws', name='modelprovider'), server_default=sa.text("'huggingface'::modelprovider"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('embeddingmodel_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('embeddingmodel_pkey'))
    )
    op.create_index(op.f('ix_embeddingmodel_name'), 'embeddingmodel', ['name'], unique=False)
    op.create_table('llm_interactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('functionality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('output_data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feedback_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feedback_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('llm_interactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_interactions_pkey'))
    )
    op.create_index(op.f('ix_llm_interactions_functionality'), 'llm_interactions', ['functionality'], unique=False)
    op.drop_index(op.f('ix_tool_interactions_functionality'), table_name='tool_interactions')
    op.drop_table('tool_interactions')
    # ### end Alembic commands ###
