"""Add date columns to Knowledge Base table v2

Revision ID: 23f981635d08
Revises: cce9c4eaf724
Create Date: 2025-05-12 23:34:12.679084

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '23f981635d08'
down_revision = '552cec846906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge-bases', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('knowledge-bases', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge-bases', 'date_modified')
    op.drop_column('knowledge-bases', 'date_created')
    op.drop_column('knowledge-bases', 'number_of_sources')
    # ### end Alembic commands ###
