"""Update Source table to use unique ID from Source Data table

Revision ID: 2ff65632533b
Revises: ac21d255a2ba
Create Date: 2025-05-10 17:37:03.119939

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2ff65632533b'
down_revision = 'ac21d255a2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source-data_id_fkey', 'source-data', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('source-data_id_fkey', 'source-data', 'sources', ['id'], ['id'])
    # ### end Alembic commands ###
