"""Add default_llm and default_embedding_model to user

Revision ID: 4ff08e69321d
Revises: 13558e98d29a
Create Date: 2025-05-29 13:43:36.750405

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4ff08e69321d'
down_revision = '13558e98d29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
