"""Update Source table to use unique ID from Source Data table v2

Revision ID: 552cec846906
Revises: cdde59fa3b6e
Create Date: 2025-05-12 08:40:55.701153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '552cec846906'
down_revision = 'cdde59fa3b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
