"""add AWS Bedrock to model provider list v2

Revision ID: 5621ccf38147
Revises: e8b7b41b6c54
Create Date: 2025-06-03 10:47:00.997913

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5621ccf38147'
down_revision = 'e8b7b41b6c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if 'replicate' value already exists in the enum before adding it
    connection = op.get_bind()
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_enum WHERE enumlabel = 'aws' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'modelprovider')")
    ).fetchone()
    
    if result is None:
        op.execute("ALTER TYPE modelprovider ADD VALUE 'aws'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
