"""Make knowledge base title unique per user

Revision ID: 626b556489c5
Revises: b98d041fe59c
Create Date: 2025-05-24 09:02:17.025321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '626b556489c5'
down_revision = 'b98d041fe59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knowledge-bases_title_key', 'knowledge-bases', type_='unique')
    op.create_unique_constraint('uq_knowledgebase_title_owner', 'knowledge-bases', ['title', 'owner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_knowledgebase_title_owner', 'knowledge-bases', type_='unique')
    op.create_unique_constraint('knowledge-bases_title_key', 'knowledge-bases', ['title'])
    # ### end Alembic commands ###
