"""Convert default_llm column from UUID to VARCHAR

Revision ID: 6e967abca8e8
Revises: 9cc09111f243
Create Date: 2025-07-05 08:08:31.145854

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "6e967abca8e8"
down_revision = "9cc09111f243"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint if it exists
    try:
        op.drop_constraint("user_default_llm_fkey", "user", type_="foreignkey")
    except Exception:
        # Constraint might not exist
        pass

    # Add a temporary column with the string values
    op.add_column(
        "user", sa.Column("default_llm_temp", sa.String(length=100), nullable=True)
    )

    # Set default value for the temporary column
    op.execute(
        "UPDATE \"user\" SET default_llm_temp = 'gpt-4o-mini' WHERE default_llm IS NOT NULL"
    )

    # Drop the original UUID column
    op.drop_column("user", "default_llm")

    # Rename the temporary column to the original name
    op.alter_column("user", "default_llm_temp", new_column_name="default_llm")

    # Set default for any NULL values
    op.execute(
        "UPDATE \"user\" SET default_llm = 'gpt-4o-mini' WHERE default_llm IS NULL"
    )

    # Make the column NOT NULL
    op.alter_column(
        "user", "default_llm", existing_type=sa.String(length=100), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make the column nullable
    op.alter_column(
        "user", "default_llm", existing_type=sa.String(length=100), nullable=True
    )

    # This downgrade is not straightforward as we can't convert string back to UUID
    # We could create a new UUID column and set it to NULL, but that would lose data
    # For now, just comment that this is a one-way migration
    # op.alter_column('user', 'default_llm', existing_type=sa.String(length=100), type_=sa.UUID())
    # ### end Alembic commands ###
