"""remove case sensitivity from provider list

Revision ID: 6f41ba5b546d
Revises: 853fb7074829
Create Date: 2025-05-17 09:10:50.266171

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f41ba5b546d'
down_revision = '853fb7074829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
