"""Remove data column from knowledge-bases table

Revision ID: 7b94b6c142de
Revises: 5621ccf38147
Create Date: 2025-06-22 15:54:25.561562

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "7b94b6c142de"
down_revision = "5621ccf38147"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge-bases", "data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge-bases", sa.Column("data", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###
