"""Add provider column to SQL table of embedding models

Revision ID: 853fb7074829
Revises: e3374c2f0ffe
Create Date: 2025-05-17 09:02:16.679821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '853fb7074829'
down_revision = 'e3374c2f0ffe'
branch_labels = None
depends_on = None


def upgrade():
    # MANUAL FIXED BY DAVID TO ADD TYPE
    # Create the enum type first
    modelprovider = sa.Enum('huggingface', 'openai', name='modelprovider')
    modelprovider.create(op.get_bind(), checkfirst=True)
    
    # Then add the column using the created enum type
    op.add_column('embeddingmodel', 
                 sa.Column('provider', 
                          sa.Enum('huggingface', 'openai', 
                                 name='modelprovider'), 
                          server_default='huggingface',  # Add a default value
                          nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddingmodel', 'provider')
    sa.Enum(name='modelprovider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
