"""Fix Source table composite key

Revision ID: 8dd1ef36829a
Revises: 2ff65632533b
Create Date: 2025-05-10 17:40:17.527665

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8dd1ef36829a'
down_revision = '2ff65632533b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
