"""Add owner_id to forms table v2

Revision ID: 8f2df8252272
Revises: cabdfa66122d
Create Date: 2025-05-14 18:30:30.323546

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8f2df8252272'
down_revision = 'cabdfa66122d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'forms', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'owner_id')
    # ### end Alembic commands ###
