"""make_embedding_models_required_on_users_and_knowledge_bases

Revision ID: 9cc09111f243
Revises: b66798c318d0
Create Date: 2025-07-04 18:11:31.747948

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "9cc09111f243"
down_revision = "b66798c318d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update any NULL values with a default value before making the columns NOT NULL
    # For users table - make default_embedding_model NOT NULL
    op.execute(
        "UPDATE \"user\" SET default_embedding_model = 'text-embedding-3-small' WHERE default_embedding_model IS NULL"
    )
    op.alter_column(
        "user",
        "default_embedding_model",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )

    # For knowledge-bases table - first convert UUID to VARCHAR(100), then make it NOT NULL
    # First, drop the foreign key constraint
    op.drop_constraint(
        "knowledge-bases_embedding_model_id_fkey", "knowledge-bases", type_="foreignkey"
    )

    # Add a temporary column with the string values
    op.add_column(
        "knowledge-bases",
        sa.Column("embedding_model_id_temp", sa.String(length=100), nullable=True),
    )

    # Populate the temporary column with the converted values
    op.execute(
        """
        UPDATE "knowledge-bases" 
        SET embedding_model_id_temp = (
            SELECT em.model_id 
            FROM embeddingmodel em 
            WHERE em.id = "knowledge-bases".embedding_model_id
        )
        WHERE embedding_model_id IS NOT NULL
        """
    )

    # Drop the original UUID column
    op.drop_column("knowledge-bases", "embedding_model_id")

    # Rename the temporary column to the original name
    op.alter_column(
        "knowledge-bases",
        "embedding_model_id_temp",
        new_column_name="embedding_model_id",
    )

    # Set default for NULL values
    op.execute(
        "UPDATE \"knowledge-bases\" SET embedding_model_id = 'text-embedding-3-small' WHERE embedding_model_id IS NULL"
    )

    # Make the column NOT NULL
    op.alter_column(
        "knowledge-bases",
        "embedding_model_id",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make the columns nullable again
    op.alter_column(
        "knowledge-bases",
        "embedding_model_id",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "user",
        "default_embedding_model",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    # ### end Alembic commands ###
