"""Update Source table to allow duplicate IDs

Revision ID: ac21d255a2ba
Revises: 7b1fb4ddb0de
Create Date: 2025-05-10 17:31:21.110185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac21d255a2ba'
down_revision = '7b1fb4ddb0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sources', 'source-data', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    # ### end Alembic commands ###
