"""Add file storage fields to KnowledgeBase

Revision ID: add_file_storage_fields
Revises: 
Create Date: 2025-09-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_file_storage_fields'
down_revision = 'e6ed8cd1320e'  # This will need to be updated with the latest revision
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge-bases', sa.Column('file_path', sa.String(length=512), nullable=True))
    op.add_column('knowledge-bases', sa.Column('storage_type', sa.String(length=20), nullable=False, server_default='database'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge-bases', 'storage_type')
    op.drop_column('knowledge-bases', 'file_path')
    # ### end Alembic commands ###