"""First attempt at adding a table for LLMs

Revision ID: b4d3726cdfff
Revises: 6f41ba5b546d
Create Date: 2025-05-19 13:35:57.720079

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4d3726cdfff'
down_revision = '6f41ba5b546d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE modelprovider ADD VALUE IF NOT EXISTS 'ollama'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
