"""Add default_llm and default_embedding_model to user 2

Revision ID: b7749e208d21
Revises: 4ff08e69321d
Create Date: 2025-05-29 13:53:15.357697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b7749e208d21'
down_revision = '4ff08e69321d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_llm', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('default_embedding_model', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'llmmodel', ['default_llm'], ['id'])
    op.create_foreign_key(None, 'user', 'embeddingmodel', ['default_embedding_model'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'default_embedding_model')
    op.drop_column('user', 'default_llm')
    # ### end Alembic commands ###
