"""Add Replicate to list of modelproviders

Revision ID: b98d041fe59c
Revises: 006e47239e5c
Create Date: 2025-05-22 19:43:51.483066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b98d041fe59c'
down_revision = '006e47239e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE modelprovider ADD VALUE 'replicate'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
