"""Add forms table

Revision ID: bbccf79299a2
Revises: 23f981635d08
Create Date: 2025-05-14 17:35:50.126112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbccf79299a2'
down_revision = '23f981635d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge-bases', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('knowledge-bases', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge-bases', 'date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge-bases', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
