"""add feedback columns to llm_interactions table

Revision ID: bf981d0ebab5
Revises: e188173ad20a
Create Date: 2025-05-31 23:40:44.811537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bf981d0ebab5'
down_revision = 'e188173ad20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_interactions', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('llm_interactions', sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('llm_interactions', sa.Column('feedback_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_interactions', 'feedback_date')
    op.drop_column('llm_interactions', 'feedback_text')
    op.drop_column('llm_interactions', 'feedback')
    # ### end Alembic commands ###
