"""Fix Source table composite key v2

Revision ID: c2d2f2aa6be7
Revises: 8dd1ef36829a
Create Date: 2025-05-10 17:41:31.495821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c2d2f2aa6be7'
down_revision = '8dd1ef36829a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
