"""Add owner_id to forms table

Revision ID: cabdfa66122d
Revises: 7224a66210cb
Create Date: 2025-05-14 18:27:09.345793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cabdfa66122d'
down_revision = '7224a66210cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
