"""add_llm_interaction_tracking_table v2

Revision ID: cd1f61be683c
Revises: 0795a7f4628e
Create Date: 2025-05-30 09:38:04.281222

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd1f61be683c'
down_revision = '0795a7f4628e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
