"""Fix Source table composite key v3

Revision ID: cdde59fa3b6e
Revises: c2d2f2aa6be7
Create Date: 2025-05-10 17:52:25.449270

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cdde59fa3b6e'
down_revision = 'c2d2f2aa6be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source_data_id', sa.Uuid(), nullable=False))
    op.drop_constraint('sources_id_fkey', 'sources', type_='foreignkey')
    op.create_foreign_key(None, 'sources', 'source-data', ['source_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.create_foreign_key('sources_id_fkey', 'sources', 'source-data', ['id'], ['id'])
    op.drop_column('sources', 'source_data_id')
    # ### end Alembic commands ###
