"""attempt to remove is_default column from model tables

Revision ID: e0bbef8fc60f
Revises: b7749e208d21
Create Date: 2025-05-29 14:11:30.381025

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e0bbef8fc60f'
down_revision = 'b7749e208d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddingmodel', 'is_default')
    op.drop_column('llmmodel', 'is_default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llmmodel', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('embeddingmodel', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
