"""add_llm_interaction_tracking_table v4

Revision ID: e188173ad20a
Revises: 30e409aa3661
Create Date: 2025-05-30 10:41:47.697358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e188173ad20a'
down_revision = '30e409aa3661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('functionality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_interactions_functionality'), 'llm_interactions', ['functionality'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_interactions_functionality'), table_name='llm_interactions')
    op.drop_table('llm_interactions')
    # ### end Alembic commands ###
