"""Add embedding model column to knowledge-bases SQL table

Revision ID: e3374c2f0ffe
Revises: be41122922e3
Create Date: 2025-05-16 16:51:55.198878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e3374c2f0ffe'
down_revision = 'be41122922e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge-bases', sa.Column('embedding_model_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'knowledge-bases', 'embeddingmodel', ['embedding_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge-bases', type_='foreignkey')
    op.drop_column('knowledge-bases', 'embedding_model_id')
    # ### end Alembic commands ###
