"""add AWS Bedrock to model provider list

Revision ID: e8b7b41b6c54
Revises: b4d5c05101a1
Create Date: 2025-06-03 10:41:10.673825

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e8b7b41b6c54'
down_revision = 'b4d5c05101a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
