"""Add data column to KnowledgeBase

Revision ID: eaf8ffa5f798
Revises: 2d16b2c7a365
Create Date: 2025-05-09 11:49:20.952846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eaf8ffa5f798'
down_revision = '2d16b2c7a365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge-bases', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge-bases', 'data')
    # ### end Alembic commands ###
