"""Add unique constraint to knowledge base title

Revision ID: fe67763e712a
Revises: eaf8ffa5f798
Create Date: 2025-05-10 16:24:06.469411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fe67763e712a'
down_revision = 'eaf8ffa5f798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'knowledge-bases', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge-bases', type_='unique')
    # ### end Alembic commands ###
