/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as SignupImport } from "./routes/signup"
import { Route as ResetPasswordImport } from "./routes/reset-password"
import { Route as RecoverPasswordImport } from "./routes/recover-password"
import { Route as LoginImport } from "./routes/login"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as LayoutSettingsImport } from "./routes/_layout/settings"
import { Route as LayoutReviewImport } from "./routes/_layout/review"
import { Route as LayoutModelSelectionImport } from "./routes/_layout/model-selection"
import { Route as LayoutMatchImport } from "./routes/_layout/match"
import { Route as LayoutKnowledgeBasesImport } from "./routes/_layout/knowledge-bases"
import { Route as LayoutGenerateImport } from "./routes/_layout/generate"
import { Route as LayoutFeedbackImport } from "./routes/_layout/feedback"
import { Route as LayoutCompareImport } from "./routes/_layout/compare"
import { Route as LayoutArchiveImport } from "./routes/_layout/archive"
import { Route as LayoutAdminImport } from "./routes/_layout/admin"

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: "/signup",
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: "/reset-password",
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: "/recover-password",
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: "/settings",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReviewRoute = LayoutReviewImport.update({
  path: "/review",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutModelSelectionRoute = LayoutModelSelectionImport.update({
  path: "/model-selection",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMatchRoute = LayoutMatchImport.update({
  path: "/match",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutKnowledgeBasesRoute = LayoutKnowledgeBasesImport.update({
  path: "/knowledge-bases",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGenerateRoute = LayoutGenerateImport.update({
  path: "/generate",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFeedbackRoute = LayoutFeedbackImport.update({
  path: "/feedback",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCompareRoute = LayoutCompareImport.update({
  path: "/compare",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutArchiveRoute = LayoutArchiveImport.update({
  path: "/archive",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: "/admin",
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/recover-password": {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    "/reset-password": {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    "/signup": {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    "/_layout/admin": {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/archive": {
      preLoaderRoute: typeof LayoutArchiveImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/compare": {
      preLoaderRoute: typeof LayoutCompareImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/feedback": {
      preLoaderRoute: typeof LayoutFeedbackImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/generate": {
      preLoaderRoute: typeof LayoutGenerateImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/knowledge-bases": {
      preLoaderRoute: typeof LayoutKnowledgeBasesImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/match": {
      preLoaderRoute: typeof LayoutMatchImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/model-selection": {
      preLoaderRoute: typeof LayoutModelSelectionImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/review": {
      preLoaderRoute: typeof LayoutReviewImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/settings": {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/": {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutArchiveRoute,
    LayoutCompareRoute,
    LayoutFeedbackRoute,
    LayoutGenerateRoute,
    LayoutKnowledgeBasesRoute,
    LayoutMatchRoute,
    LayoutModelSelectionRoute,
    LayoutReviewRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
