#! /usr/bin/env bash

set -e
set -x

echo "Starting the generate-client script..."

# Detect the operating system
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    echo "Detected macOS"
    cd backend
    uv run python -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
    cd ..
    mv openapi.json frontend/
    cd frontend
    npm run generate-client
    npx biome format --write ./src/client
    # Run the patch script
    node ../scripts/patch-autogenerated-client-code.js
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "win32" ]]; then
    # Windows (Git Bash, Cygwin, or native Windows)
    echo "Detected Windows"
    cd backend
    /mnt/c/miniconda/aibeniq-react/backend/.venv/Scripts/python.exe -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
    cd ..
    mv openapi.json frontend/
    cd frontend
    cmd.exe /c npm-with-node.bat run generate-client
    cmd.exe /c npm-with-node.bat run format
    # Run the patch script
    cmd.exe /c "set PATH=C:\Users\David Abugaber\AppData\Local\fnm_multishells\10244_1748038819980;%CD%\node_modules\.bin;%PATH% && node ../scripts/patch-autogenerated-client-code.js"
else
    # Linux or other Unix-like systems
    echo "Detected Linux/Unix"
    cd backend
    python -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
    cd ..
    mv openapi.json frontend/
    cd frontend
    npm run generate-client
    npx biome format --write ./src/client
    # Run the patch script
    node ../scripts/patch-autogenerated-client-code.js
fi

