#! /usr/bin/env bash

set -e
set -x

echo "Starting the generate-client script..."

# Check if we're in the correct directory structure
if [ ! -d "backend" ] || [ ! -d "frontend" ]; then
    echo "Error: Please run this script from the project root directory"
    echo "Expected directories: backend/ and frontend/"
    exit 1
fi

# Detect the operating system
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    echo "Detected macOS"
    cd backend
    # Try to use virtual environment if it exists, otherwise use system python
    if [ -d ".venv" ]; then
        echo "Using virtual environment"
        source .venv/bin/activate
        python -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
    else
        echo "Using system python"
        # Try different python executables
        if command -v python3 &> /dev/null; then
            echo "Using python3"
            python3 -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
        elif command -v python &> /dev/null; then
            echo "Using python"
            python -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
        else
            echo "Error: No Python executable found"
            exit 1
        fi
    fi
    cd ..
    
    # Check if OpenAPI generation was successful
    if [ ! -f "openapi.json" ]; then
        echo "Error: Failed to generate openapi.json"
        exit 1
    fi
    
    mv openapi.json frontend/
    cd frontend
    npm run generate-client
    npx biome format --write ./src/client
    # Run the patch script
    node ../scripts/patch-autogenerated-client-code.js
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "win32" ]]; then
    # Windows (Git Bash, Cygwin, or native Windows)
    echo "Detected Windows"
    cd backend
    /mnt/c/miniconda/aibeniq-react/backend/.venv/Scripts/python.exe -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
    cd ..
    mv openapi.json frontend/
    cd frontend
    cmd.exe /c npm-with-node.bat run generate-client
    cmd.exe /c npm-with-node.bat run format
    # Run the patch script
    cmd.exe /c "set PATH=C:\Users\David Abugaber\AppData\Local\fnm_multishells\10244_1748038819980;%CD%\node_modules\.bin;%PATH% && node ../scripts/patch-autogenerated-client-code.js"
else
    # Linux or other Unix-like systems
    echo "Detected Linux or other Unix-like system"
    cd backend
    python -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
    cd ..
    mv openapi.json frontend/
    cd frontend
    npm run generate-client
    npx biome format --write ./src/client
    # Run the patch script
    node ../scripts/patch-autogenerated-client-code.js
fi

