#! /usr/bin/env bash

set -e
set -x

echo "Starting the generate-client script..."

cd backend


if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" || "$OSTYPE" == "cygwin" ]]; then
    # Windows
    PYTHON_PATH="/mnt/c/miniconda/aibeniq-react/backend/.venv/Scripts/python.exe"
    NPM_CMD="cmd.exe /c npm-with-node.bat"
    PATCH_CMD='cmd.exe /c "set PATH=C:\Users\David Abugaber\AppData\Local\fnm_multishells\10244_1748038819980;%CD%\node_modules\.bin;%PATH% && node ../scripts/patch-autogenerated-client-code.js"'
else
    # Linux/macOS
    echo $PWD
    source .venv/bin/activate
    PYTHON_PATH="python"
    NPM_CMD="npm"
    PATCH_CMD="node ../scripts/patch-autogenerated-client-code.js"
fi

$PYTHON_PATH -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" > ../openapi.json
cd ..
mv openapi.json frontend/
cd frontend

$NPM_CMD run generate-client
$NPM_CMD run format

# Run the patch script to add responseType: 'blob' to the generated client
eval $PATCH_CMD