apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  ENVIRONMENT: "development"
  BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173,https://dashboard-dev.yourdomain.com"
