apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  ENVIRONMENT: "production"
  BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173,http://redhat.aiben.io"
  FRONTEND_HOST: "http://redhat.aiben.io"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_API_URL: "http://redhat-api.aiben.io"
