apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aibeniq-development

resources:
  - ../../base

namespace: aibeniq-dev

patchesStrategicMerge:
  - internal-registry-patches.yaml
  - configmap-patch.yaml
  - backend-patch.yaml
  - backend-memory-patch.yaml # Memory optimization for ML installations
  - route-patches.yaml
  - ml-config-patch.yaml

commonLabels:
  environment: development

images:
  # Map frontend image from aibeniq-prod to internal registry aibeniq-dev
  - name: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/frontend
    newName: image-registry.openshift-image-registry.svc:5000/aibeniq-dev/frontend
    newTag: latest
