apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aibeniq-development

resources:
  - ../../base

namespace: aibeniq-dev

patchesStrategicMerge:
  - domain-config-patch.yaml
  - configmap-patch.yaml
  - backend-patch.yaml
  # internal registry now handled via images block

commonLabels:
  environment: development

images:
  - name: quay.io/aibeniq/backend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-dev/backend
    newTag: latest
  - name: quay.io/aibeniq/frontend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-dev/frontend
    newTag: latest
