apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aibeniq-development

resources:
  - ../../base

namespace: aibeniq-dev

patchesStrategicMerge:
  - internal-registry-patches.yaml
  - configmap-patch.yaml
  - backend-patch.yaml
  - route-patches.yaml

commonLabels:
  environment: development

images:
  # Map external route images
  - name: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/backend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-dev/backend
    newTag: latest
  - name: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/frontend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-dev/frontend
    newTag: latest
  # Map internal service images
  - name: image-registry.openshift-image-registry.svc:5000/aibeniq-prod/backend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-dev/backend
    newTag: latest
