---
# Patch backend deployment to use internal registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: image-registry.openshift-image-registry.svc:5000/aibeniq-prod/backend:dashboard-redhat-cf4002b
---
# Patch frontend deployment to use internal registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: image-registry.openshift-image-registry.svc:5000/aibeniq-prod/frontend:latest
---
# Patch backend prestart job to use internal registry
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-prestart
spec:
  template:
    spec:
      containers:
        - name: backend-prestart
          image: image-registry.openshift-image-registry.svc:5000/aibeniq-prod/backend:dashboard-redhat-cf4002b
