apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aibeniq-production

resources:
  - ../../base

namespace: aibeniq-prod

patchesStrategicMerge:
  # Only remaining patch is backend dev sizing in development overlay; production has no resource patches now

commonLabels:
  environment: production # Reverting to commonLabels due to oc/kustomize version schema

images:
  - name: quay.io/aibeniq/backend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/backend
    newTag: latest
  - name: quay.io/aibeniq/frontend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/frontend
    newTag: latest
