apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aibeniq-production

resources:
  - ../../base

namespace: aibeniq-prod

patchesStrategicMerge:
  - ml-config-patch.yaml
  - configmap-patch.yaml
  - secret-patch.yaml
  - backend-memory-patch.yaml # Memory optimization for ML installations
  - internal-registry-patches.yaml

commonLabels:
  environment: production # Reverting to commonLabels due to oc/kustomize version schema

images:
  - name: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/backend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/backend
    newTag: latest
  - name: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/frontend
    newName: default-route-openshift-image-registry.apps.aibeniq-prod.gimc.p1.openshiftapps.com/aibeniq-prod/frontend
    newTag: latest
